apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-container-deployment
  labels:
    app: test-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-container
  template:
    metadata:
      labels:
        app: test-container
    spec:
      containers:
        - name: test-container
          image: tanguangbin1980/test-dev:7  # 这里会被 Jenkins 替换为实际的镜像名称       
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"  # 默认设置为 dev，可以在 Jenkinsfile 中动态修改
---
apiVersion: v1
kind: Service
metadata:
  name: test-container-service
spec:
  type: NodePort
  ports:
    - port: 8081  # Service 的端口
      targetPort: 8081  # 容器中的端口
      nodePort: 30011  # 在每个 Node 上的端口（30000-32767）
  selector:
    app: test-container
