server:
  port: 8082

tangb: dev
mybatis-plus:
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
# spring:
#   datasource:
#     url: jdbc:mysql://localhost:3306/tan-vue-pro?rewriteBatchedStatements=true
#     username: root
#     password: 1234
#     driver-class-name: com.mysql.cj.jdbc.Driver
